name: Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
        with:
          path: ${{ github.event.repository.name }}
            
      - name: Checkout `worlds`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/worlds
          token: ${{ secrets.PAT }}
          path: worlds
      
      - name: Checkout `simulation`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/simulation
          token: ${{ secrets.PAT }}
          path: simulation
      
      - name: Checkout `physics`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/physics
          token: ${{ secrets.PAT }}
          path: physics
      
      - name: Checkout `unmanaged`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/unmanaged
          token: ${{ secrets.PAT }}
          path: unmanaged
      
      - name: Checkout `transform-systems`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/transform-systems
          token: ${{ secrets.PAT }}
          path: transform-systems
      
      - name: Checkout `transforms`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/transforms
          token: ${{ secrets.PAT }}
          path: transforms
      
      - name: Checkout `types`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/types
          token: ${{ secrets.PAT }}
          path: types
      
      - name: Checkout `shapes`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/shapes
          token: ${{ secrets.PAT }}
          path: shapes
      
      - name: Checkout `collections`
        uses: actions/checkout@v4.1.2
        with:
          repository: simulation-tree/collections
          token: ${{ secrets.PAT }}
          path: collections
            
      - name: Setup
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Set VERSION variable from tag
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
            
      - name: Build `Physics.Systems`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Debug /p:Version=${VERSION}
      
      - name: Build `Physics.Systems`
        run: dotnet build "${{ github.event.repository.name }}/source" -c Release /p:Version=${VERSION}
      
      - name: Build `Physics.Systems.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Debug /p:Version=${VERSION}
      
      - name: Build `Physics.Systems.Tests`
        run: dotnet build "${{ github.event.repository.name }}/tests" -c Release /p:Version=${VERSION}
            
      - name: Test
        run: dotnet test "${{ github.event.repository.name }}/tests" -c Release --logger "trx"
            
      - name: Pack `Physics.Systems`
        run: dotnet pack "${{ github.event.repository.name }}/source" /p:Version=${VERSION} --no-build --output .

      - name: Add NuGet Source
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github --username ${{ github.repository_owner }} --password ${{ github.token }} --store-password-in-clear-text
            
      - name: Publish `Physics.Systems`
        run: dotnet nuget push Physics.Systems.${VERSION}.nupkg --source github --api-key ${NUGET_TOKEN}
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}